server:
  port: 9000
kafka:
  bootstrapAddress: localhost:9092
  bootstrapAddress2: localhost:39092
spring:
  output:
    ansi:
      enabled: always
message:
  topic:
    name: message-log
    group:
      id: group_id

user:
    topic:
      name: user-log
      group:
        id: group_id